// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetDistinctCityAndCustomerOrderByCountry(ctx context.Context) ([]GetDistinctCityAndCustomerOrderByCountryRow, error)
	GetDistinctCityOrderByCity(ctx context.Context) ([]sql.NullString, error)
	GetDistinctCompany(ctx context.Context) ([]sql.NullString, error)
}

var _ Querier = (*Queries)(nil)
