// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mysql

import (
	"database/sql"
)

type Author struct {
	ID   int32          `json:"id"`
	Name string         `json:"name"`
	Bio  sql.NullString `json:"bio"`
}

type Book struct {
	ID            int32          `json:"id"`
	Title         string         `json:"title"`
	AuthorID      int32          `json:"author_id"`
	PublishedYear sql.NullInt32  `json:"published_year"`
	Genre         sql.NullString `json:"genre"`
	Description   sql.NullString `json:"description"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
